remote_theme: pages-themes/time-machine@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one
title: Aarnav Jayesh Mishra
description: Data Analyst leveraging SQL and Python for in-depth data analysis. Dedicated to creating interactive dashboards and actionable recommendations for decision-makers.
